name: Vislocas
channels:
  - iopath
  - fvcore
  - pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20210915=py38
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=py38
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=26_linux64_mkl
  - libcblas=3.9.0=26_linux64_mkl
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=26_linux64_mkl
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.3.1=py38h06a4308_0
  - portalocker=2.3.0=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.15=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py38h0a891b7_4
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h5082296_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - termcolor=2.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - typing-extensions=4.4.0=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.13=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.2.0
    - accelerate==0.34.2
    - adabelief-pytorch==0.2.0
    - addict==2.4.0
    - aiohappyeyeballs==2.4.0
    - aiohttp==3.10.5
    - aiosignal==1.3.1
    - anyio==3.6.1
    - apex==0.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - async-timeout==4.0.3
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - bytecode==0.16.0
    - cachetools==5.1.0
    - calflops==0.3.2
    - chardet==4.0.0
    - colorama==0.4.5
    - cycler==0.11.0
    - d2l==0.17.6
    - dcn==1.0
    - debugpy==1.6.0
    - defusedxml==0.7.1
    - einops==0.6.0
    - executing==1.2.0
    - fastjsonschema==2.16.1
    - fonttools==4.37.1
    - frozenlist==1.4.1
    - fsspec==2024.9.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - grad-cam==1.5.4
    - grpcio==1.51.1
    - huggingface-hub==0.25.0
    - idna==2.10
    - importlib-metadata==5.1.0
    - importlib-resources==5.9.0
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.1
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.8.0
    - jupyter==1.0.0
    - jupyter-client==7.3.4
    - jupyter-console==6.4.4
    - jupyter-core==5.0.0
    - jupyter-server==1.23.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.2
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mdurl==0.1.2
    - mistune==2.0.4
    - mmcls==0.25.0
    - mmcv==1.7.2
    - multidict==6.0.5
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - nest-asyncio==1.5.4
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.24.4
    - oauthlib==3.2.2
    - opencv-python==4.6.0.66
    - packaging==21.0
    - pandas==1.2.4
    - pandocfilters==1.5.0
    - platformdirs==4.3.6
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.33
    - protobuf==3.20.3
    - psutil==5.9.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.19.1
    - pyrsistent==0.19.2
    - pytz==2022.6
    - pyzmq==24.0.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - regex==2024.9.11
    - requests==2.25.1
    - requests-oauthlib==1.3.1
    - rich==13.9.4
    - rsa==4.9
    - safetensors==0.4.5
    - scikit-learn==1.1.2
    - scipy==1.9.3
    - send2trash==1.8.0
    - simplejson==3.18.0
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.1
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.17.0
    - threadpoolctl==3.1.0
    - timm==1.0.9
    - tinycss2==1.1.1
    - tokenizers==0.19.1
    - tomli==2.2.1
    - torch-cluster==1.6.0
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.1.0
    - torch-sparse==0.6.15
    - torch-spline-conv==1.2.1
    - torchsummary==1.5.1
    - tornado==6.1
    - tqdm==4.63.1
    - traitlets==5.5.0
    - transformers==4.44.2
    - ttach==0.0.3
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.2
    - yapf==0.43.0
    - yarl==1.9.10
    - zipp==3.11.0
prefix: /mnt/T19/anaconda3/envs/Vislocas
